package com.jaehi.molcardogam

import com.jaehi.molgam.R

object MolcarData {
    val molcarList = listOf<Molcar>(
        Molcar("포테토",
            R.drawable.molcar_potato,"느긋한 성격이지만 종종 운전자의 조종을 무시할 때가 있으며 도움이 필요한 이에게 거리낌 없기도 하다. 당근을 제일 좋아한다.",1),
        Molcar("시로모", R.drawable.molcar_siromo, "겁이 많은 모루카 중에서도 특히 겁이 많다.\n마음씨 좋은 운전자에게 응석을 부리기도 하지만 여러 트러블에 휘말려 들 때가 많다.\n테디를 누님처럼 따르고 있다.\n제일 좋아하는것은 양상추다.",1),
        Molcar("좀비 시로모", R.drawable.zombie_siromo , "좀비에게 물려 감염되어 버린 시로모다.\n주식은 고기다.",1),
        Molcar( "테디", R.drawable.molcar_teddy,   "무엇이든 잘 먹고 잘 움직인다.\n말괄량이에 겁이 없다.\n엉뚱한 행동을 하는 말썽꾸러기라서 주위의 걱정을 사고있다.\n모티브는 털이 곱슬곱슬한 테디 기니피그이다.",1),
        Molcar( "아비", R.drawable.molcar_abi,   "성실하고 호기심이 왕성하다.\n초보자 운전 마크를 달고 있지만 언젠가 초보 운전을 졸업하기를 꿈꾸고 있다.\n고양이를 싫어한다.",1),
        Molcar( "이타샤 아비", R.drawable.otaku_abi,   "오타쿠인 드라이버에 의해 마법천사 모루미가 그려진 아비.\n본인은 맘에 들지 않는 듯하다.",1),
        Molcar( "초코", R.drawable.molcar_choco  ,   "상큼하고 부드러운 성격 같지만 의외로 힘이 세고 신체 능력에 특화된 면이 있는것 같다.\n깨끗한 것을 좋아하고 외모에도 신경을 쓰고 있다.\n언젠가 No.1 고급 모루카가 되는것이 꿈이다.",1),
        Molcar("지니",   R.drawable.molcar_ginnie,   "항아리 같이 작은 물건에 숨는 것이 특기인 모루카다.\n지니지만 소원을 이루어주진 못한다.",1),
        Molcar("폰타",  R.drawable.molcar_pontta,   "모래를 가지고 노는 것을 제일 좋아한다.",1),
        Molcar( "로즈", R.drawable.molcar_rose,   "몸 치장에 매우 공을 들인다.\n예전에 길거리에서 이타샤 아비가 고양이를 구하는 모습을 목격하고 관심이 생겼다.",1),
        Molcar( "히터",   R.drawable.molcar_hitter,   "드라이버의 신발을 항상 따뜻하게 데우고 있다.",1),
        Molcar("민트초코",   R.drawable.molcar_mintchoco,   "여름에 잘 어울리는 모루카다.\n치약 선전에 쓰일 뻔 했지만 드라이버에게 제지당했다.",1),
        Molcar( "히말라양",   R.drawable.molcar_himallayang,   "설인이 실존한다고 믿고 있다.",1),
        Molcar("오닉스",   R.drawable.molcar_onix,   "드라이버가 부자여서 언제나 최고급 식사를 대접받지만 정작 본인은 잡초와 구별을 못한다.",1),
        Molcar("플레튼",   R.drawable.molcar_platten,   "도망치는것이 특기다.\n속도에 깜짝 놀란다.",1),
        Molcar( "키드",   R.drawable.molcar_kid,   "외모 때문인지 종종 강도로 오해받아 검문을 당하기도 하는 안타까운 모루카다.",1),
        Molcar( "포폼",   R.drawable.molcar_popom,   "우주와 통신을 하는듯 하다.",1),
        Molcar( "오드",   R.drawable.molcar_odd,   "삼색의 털을 가지고 있다.\n모루카계 나르시스트다.",1),
        Molcar( "타라코",   R.drawable.molcar_taraco,   "DJ 모루카와 사이가 좋다.",1),
        Molcar( "고로케",   R.drawable.molcar_gorokae,   "모루카답지 않게 고양이를 좋아한다.",1),
        Molcar( "차이",   R.drawable.molcar_cahi,   "인도에서 왔다.",1),
        Molcar( "텐텐 & 통통",   R.drawable.molcar_tentong,   "아래는 텐텐 위에는 통통\n쌍둥이 모루카다.",1),
        Molcar( "깨소금",   R.drawable.molcar_kkaesogeum,   "부끄럼쟁이라 거의 모습을 드러내지 않는다.",1),
        Molcar(  "참깨",   R.drawable.molcar_chamkkae,   "마이페이스 쿨한 성격이지만 느림보다.",1),
        Molcar("링거",   R.drawable.molcar_linger,   "댄스라면 따라올 모루카가 없다.",1),
        Molcar(  "스컹크",   R.drawable.molcar_skunk,   "이름과 다르게 의외로 좋은 냄새가 난다.",1),
        Molcar( "민들레",   R.drawable.molcar_mindeullae,   "민들레 홀씨 같이 하얗다.\n민들레를 자주 먹는다.",1),
        Molcar( "시나",   R.drawable.molcar_sina,   "꽃을 좋아하는 모루카다.\n너무 좋아한 나머지 꽃에게 말을 걸고 먹어버린다.",1),
        Molcar( "바나나",   R.drawable.molcar_banana,   "이름과 다르게 바나나보다 아삭채를 더 좋아한다.",1),
        Molcar(  "제리",   R.drawable.molcar_jerry,   "누구도 말릴 수 없는 자유로운 영혼이다.",1),
        Molcar( "오카카",   R.drawable.molcar_okaka,   "카카오와 닮은 듯 안 닮은 듯하다.\n이웃사촌인 카카오와 헷갈리지 않도록 하자.",1),
        Molcar( "카카오",   R.drawable.molcar_cacao,   "카카오처럼 피부가 새까만 모루카다.\n오카카와 이웃사촌이다.",1),
        Molcar( "새우 초밥 모루카",   R.drawable.molcar_sae_u,   "쌀알 같은 털 위에 새우가 있다.\n맛있어 보인다고 먹지 않도록 주의하자.",1),
        Molcar("와사비 모루카",   R.drawable.molcar_wasabi,   "오이를 정말 좋아한다.\n무슨 일이 일어나도 오이를 먹고있을 땐 만사태평이다.",1),
        Molcar( "타임 모루카",   R.drawable.molcar_time,   "박사가 만든 개조형 모루카다.\n야채를 먹으면 과거나 미래로 갈 수 있는 특별한 능력을 가지고 있다.",1),
        Molcar( "구급 모루카",   R.drawable.molcar_emble,   "작은 생명을 구하기 위해 환자를 이송하는 모루카다.\n사람에 대한 애정이 많고 용감하다.\n교통정체로 병원에 가는 것이 지체되면 걱정되어 울음을 터뜨린다.",1),
        Molcar( "폴리스 모루카",   R.drawable.molcar_police,   "정의로운 폴리스 모루카다.\n팀워크로 뭉쳐 범인을 쫓지만 먹을 것에 약하다.",1),
        Molcar("환경 미화 모루카",   R.drawable.molcar_clean,   "쓰레기를 등에 한가득 지고 운반하는 모루카다.\n깜짝 놀라면 쓰레기를 떨어뜨리기도 한다.",1),
        Molcar( "DJ 모루카",   R.drawable.molcar_dj,   "헤드폰을 쓰고있다.\n클럽이나 파티에 자주 초대된다.\n드라이버가 운전 중에 음악을 듣거나 게임을 해서 교통체증을 일으키기도 한다.",1),
        Molcar("택시 모루카",   R.drawable.molcar_taxi,   "가고 싶은 곳은 많지만 사람을 목적지까지 태워야 한다.\n가끔씩 실수를 해도 용서해주자.",1),
        Molcar("햄버거 모루카",   R.drawable.molcar_hambuger,   "등에 커다란 햄버거를 지고 판매하는 모루카다.\n차별없이 누구에게나 친절하다.",1),
        Molcar("우편 모루카",   R.drawable.molcar_post,   "편지를 전달해주는 모루카다.\n누구보다 빠르고 정확하게 전달한다.\n편지는 엉덩이에서 나온다.",1),
        Molcar( "모험가 모루카",   R.drawable.treasuer_hunter,   "황금 당근을 구하기 위해 여러 곳을 모험하는 모루카다.\n평소에는 꼬질꼬질하지만 씻으면 아름다운 머리카락이 나타난다.",1),
        Molcar( "황금 모험가 모루카",   R.drawable.treasure_hunter_gold,"깨끗하게 씻은 모험가 모루카는 황금빛 머릿결을 갖고 있다.",1),
        Molcar("웨딩 모루카",   R.drawable.molcar_wedding,   "결혼식을 위해 꽃이 장식된 모루카다.\n장식용인 것을 잊고 그만 먹어버릴 뻔한 엉뚱한 부분이 매력 포인트다.",1),
        Molcar( "피터",   R.drawable.molcar_peter,   "겁을 잘 먹고 소심하다. 좀 어설픈 모루카다.\n언젠가 드라이버를 만난다면 아주 맛있는 당근을 받는 것이 꿈이다.",2),
        Molcar("히",R.drawable.molcar_hi,"워낙 주행을 잘해서 스카우트된 교습 모루카 리더다.\n교습 코스를 달리는 것이 어떤 것보다 나은 행복이다.",2),
        Molcar("후",R.drawable.molcar_hu,"좌우명은 인생은 클로즈업으로 보면 비극이지만 멀리서 보면 희극이다.라고 멋대로 말하고 있다.\n 좋아하는 것은 수박 껍질이다.",2),
        Molcar("미",R.drawable.molcar_mi,"공놀이와 드라이빙 스쿨의 급식을 좋아한다.\n오늘도 낮잠을 기대하고 있다.",2),
        Molcar("채소가게 모루카",   R.drawable.molcar_charso,   "매우 의젓한 모루카인데, 무려 당근, 토마토, 오이 등을 먹어치우지 않고 안전하게 배달할 수 있는 엄청난 참을성을 가졌다.\n하지만 배고프면 판매용 야채를 전부 먹어 버리기 때문에 꼭 밥을 먹고 배달을 나가야한다.",2),
        Molcar("빅토리아",R.drawable.molcar_victorya,"별명은 할머니지만 실제론 그렇지 않다.",2),
        Molcar("스프레이",R.drawable.molcar_spray,"컬러풀한 것을 좋아한다.\n드라이버도 컬러풀한 것을 좋아한다.",2),
        Molcar("계란 초밥 모루카",R.drawable.molcar_egg,"낮잠용으로 마음에 드는 매트를 짊어지고 있다.",2),
        Molcar("연어알 초밥 모루카",R.drawable.molcar_yeoneo,"기발한 모자를 쓰고 연어알 초밥 모루카가 되었다.",2),
        Molcar("밥알 초밥 모루카",R.drawable.molcar_rice,"늘 졸고 있다.\n별명은 셜리다.",2),
        Molcar("유부 초밥 모루카",R.drawable.molcar_yubu,"유부를 쓴 셜리다.\n모루카생이 달라졌다.",2),
        Molcar("우마우시",R.drawable.molcar_umausi,"수족관의 마스코트로 일하고 있다.\n물고기가 친구라고 생각한다.",2),
        Molcar("루비",R.drawable.molcar_ruby,"앞머리 세팅에 한시간이 걸린다.",2),
        Molcar("고양이",R.drawable.molcar_cat,"하치와레 고양이를 닮았기에 이름이 붙여졌다.\n고양이를 싫어한다.",2),
        Molcar("나폴리",R.drawable.molcar_napolly,"항상 달콤한 냄새에 이끌린다.",2),
        Molcar("마카로니",R.drawable.molcar_macarony,"작은 샌드위치 가게에서 배달을 돕고 있다.\n고로케랑 친하다.",2),
        Molcar("두프",R.drawable.molcar_dupe,"새에게도 놀라는 섬세한 마음을 가지고 몇 번이나 드라이빙 스쿨에서 불합격을 반복한다.\n마음에 드는 담요를 숨겨 가지고 있다.",2),
        Molcar("문버기 모루카",R.drawable.molcar_moon,"우주용으로 훈련받은 모루카.\n지구는 비가 와서 싫어한다.",2),
        Molcar("셰르",R.drawable.molcar_cherr,"사실 아는 사람만 아는 명품 모델 모루카다.\n은빛 고운 털 줄이 매력 포인트다.",2),
        Molcar("액션 모루카",R.drawable.molcar_action,"옛날에 대박이 났던 저예산 영화에 출연해서 서있던 스턴트 모루카다.",2),
    )
}

data class Molcar(
    val name : String,
    val image : Int,
    val introduce : String,
    val season : Int
)


